// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.EntitiesExaminationSystem;

public partial class Course
{
    public int CrId { get; set; }

    public string CrName { get; set; }

    public virtual ICollection<Question>? Questions { get; set; } = new List<Question>();

    public virtual ICollection<StudentCourse>? StudentCourses { get; set; } = new List<StudentCourse>();

    public virtual ICollection<Instructor>? Ins { get; set; } = new List<Instructor>();
}