// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.EntitiesExaminationSystem;

public partial class Instructor
{
    public int InsId { get; set; }

    public string InsName { get; set; }

    public decimal InsSalary { get; set; }

    public string InsDegree { get; set; }

    public int? DeptId { get; set; }

    public string Username { get; set; }

    public virtual Department Dept { get; set; }

    public virtual ICollection<Course> Crs { get; set; } = new List<Course>();
}