// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.EntitiesExaminationSystem;

public partial class QuestionChoice
{
    public int QId { get; set; }

    public string ChoiceDesc { get; set; }

    public string ChoiceSelector { get; set; }

    public virtual Question? QIdNavigation { get; set; }
}