// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.EntitiesExaminationSystem;

public partial class Question
{
    public int QId { get; set; }

    public string QHead { get; set; }

    public int QGrade { get; set; }

    public string QDifficulty { get; set; }

    public string Type { get; set; }

    public string ModelAnswer { get; set; }

    public int? CrId { get; set; }

    public virtual Course? Cr { get; set; }

    public virtual ICollection<QuestionChoice>? QuestionChoices { get; set; } = new List<QuestionChoice>();
}