// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.EntitiesExaminationSystem
{
    public partial class SP_Get_Topics_By_CourseIDResult
    {
        public string Topic_Name { get; set; }
    }
}
