// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.EntitiesExaminationSystem;

public partial class SP_Get_Student_Grade_By_IDResult
{
    [Column("Course Name")]
    public string CourseName { get; set; }
    [Column("Grade", TypeName = "decimal(5,2)")]
    public decimal? Grade { get; set; }
}
