// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.EntitiesExaminationSystem
{
    public partial class SP_Get_Questions_and_Choices_By_ExamIDResult
    {
        public int Q_ID { get; set; }
        public string Q_Head { get; set; }
        public int Q_Grade { get; set; }
        public string Q_Difficulty { get; set; }
        public string Type { get; set; }
        public string Model_Answer { get; set; }
        public int? Cr_ID { get; set; }
        public string Choice_Desc { get; set; }
        public string Choice_Selector { get; set; }
    }
}
