// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.EntitiesExaminationSystem
{
    public partial class SP_SelectAllInstructorStudentCoursesResult
    {
        [Column("Course Name")]
        public string CourseName { get; set; }
        [Column("Student Name")]
        public string StudentName { get; set; }
        [Column("Student Grade", TypeName = "decimal(5,2)")]
        public decimal? StudentGrade { get; set; }
    }
}
