// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.EntitiesExaminationSystem;

public partial class StudentCourse
{
    public int StId { get; set; }

    public int CrId { get; set; }

    public decimal? StGrade { get; set; }

    public virtual Course Cr { get; set; }

    public virtual Student St { get; set; }
}