// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.EntitiesExaminationSystem;

public partial class StudentExamQuestion
{
    public int StId { get; set; }

    public int ExamId { get; set; }

    public int QId { get; set; }

    public string StAnswer { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Question QIdNavigation { get; set; }

    public virtual Student St { get; set; }
}