// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace ExaminationSystem.EntitiesLogin;

public partial class Login
{
    public string Username { get; set; }

    public string Password { get; set; }

    public string AccountType { get; set; }
}